[[main]]
  identifier = "about"
  name = "About me"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2


# [[main]]
#  identifier = "MS365"
#  name = "Microsoft 365"
#  url = "MS365"
#  weight = 3
    
# [[main]]
#  parent = "MS365"
#  name = "Microsft 365 Admin"
#  url = "MS365/MS365_Admin"
#  weight = 1

# [[main]]
#  parent = "MS365"
#  name = "Intune"
#  url = "MS365/Intune"
#  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 5
